// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oQ_8xdVXASZJoGpKXcEWqKYE93r-1xs',
    appId: '1:231431315497:web:f665120c3b781c3b25fc38',
    messagingSenderId: '231431315497',
    projectId: 'recall-ede0f',
    authDomain: 'recall-ede0f.firebaseapp.com',
    storageBucket: 'recall-ede0f.firebasestorage.app',
    measurementId: 'G-S1RCE2PJJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAwV2Ess6JVlhNcQrPNuze6Cs9ZACbhQ',
    appId: '1:231431315497:android:f82a162e9c81401625fc38',
    messagingSenderId: '231431315497',
    projectId: 'recall-ede0f',
    storageBucket: 'recall-ede0f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS0deDysyp5vbIjCr_Ql_KTvtZIaSY75Q',
    appId: '1:231431315497:ios:f57e0b49976bae5425fc38',
    messagingSenderId: '231431315497',
    projectId: 'recall-ede0f',
    storageBucket: 'recall-ede0f.firebasestorage.app',
    iosBundleId: 'com.example.recall',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS0deDysyp5vbIjCr_Ql_KTvtZIaSY75Q',
    appId: '1:231431315497:ios:f57e0b49976bae5425fc38',
    messagingSenderId: '231431315497',
    projectId: 'recall-ede0f',
    storageBucket: 'recall-ede0f.firebasestorage.app',
    iosBundleId: 'com.example.recall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oQ_8xdVXASZJoGpKXcEWqKYE93r-1xs',
    appId: '1:231431315497:web:254ee4bf449b854e25fc38',
    messagingSenderId: '231431315497',
    projectId: 'recall-ede0f',
    authDomain: 'recall-ede0f.firebaseapp.com',
    storageBucket: 'recall-ede0f.firebasestorage.app',
    measurementId: 'G-SLSE151YXS',
  );
}
